<?php

namespace BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends EntityRepository
{
    /**
     * 
     */
    public function newComment($pid) {
        //
    }


    /**
     * 
     */
    public function removeComment($pid, $cid) {
        //
    }
}
