<?php

namespace BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends EntityRepository
{
    
    public function getAllPosts($limit) {
        //
        $qb = $this->createQueryBuilder('c')
           ->select('c')
           //->leftJoin('post', 'c')
           ->addOrderBy('c.created', 'DESC');
    
        if (false === is_null($limit))
            $qb->setMaxResults($limit);
        return $qb->getQuery()->getResult();
    }


    public function createPost($reqdata){
        //set data
        $post=new Posts();
        $post->setTitle($reqdata->request->get('title'));
        $post->setUsername($reqdata->request->get('email'));
        $post->setPost($reqdata->request->get('post'));
        $post->setCreated();
        $post->setHascomment(0);

        return $post;
    }
}
